#!/usr/bin/env python3
"""
build_index.py

Read snapshots.csv produced by crawl_sections.py and emit a Markdown index
grouping articles by section. Each article is a bullet linking to the
markdown file generated by orchestrate.py at <section>/<slug>/index.md.

Usage:
    python build_index.py snapshots.csv --output INDEX.md
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import defaultdict
from pathlib import Path


REQUIRED_COLUMNS = {"section", "slug", "title"}


def read_snapshots(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise SystemExit(f"empty CSV: {path}")
        missing = REQUIRED_COLUMNS - set(reader.fieldnames)
        if missing:
            raise SystemExit(f"CSV missing columns: {sorted(missing)}")
        return list(reader)


def md_escape(text: str) -> str:
    return text.replace("[", "\\[").replace("]", "\\]")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate a Markdown index from snapshots.csv."
    )
    ap.add_argument("snapshots", type=Path, help="CSV produced by crawl_sections.py")
    ap.add_argument("--output", type=Path, default=Path("INDEX.md"))
    args = ap.parse_args()

    if not args.snapshots.exists():
        print(f"snapshots CSV not found: {args.snapshots}", file=sys.stderr)
        return 2

    rows = read_snapshots(args.snapshots)
    if not rows:
        print("no rows in CSV", file=sys.stderr)
        return 1

    by_section: dict[str, list[dict[str, str]]] = defaultdict(list)
    for r in rows:
        by_section[r["section"]].append(r)

    lines: list[str] = []
    lines.append("# CodeProject Article Index")
    lines.append("")
    lines.append(f"{len(rows)} articles across {len(by_section)} sections.")
    lines.append("")

    for section in sorted(by_section):
        articles = sorted(
            by_section[section],
            key=lambda r: (r["title"] or r["slug"]).lower(),
        )
        lines.append(f"## {section}")
        lines.append("")
        for r in articles:
            title = md_escape(r["title"] or r["slug"])
            link = f"{r['section']}/{r['slug']}/index.md"
            lines.append(f"- [{title}]({link})")
        lines.append("")

    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.output} ({len(rows)} articles, {len(by_section)} sections)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
